production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV.fetch("PGDATABASE") { "portfoliorailsdb" } %>
  host: <%= ENV.fetch("PGHOST") { "localhost" } %>
  username: <%= ENV.fetch("PGUSER") { "app" } %>
  password: <%= ENV.fetch("PGPASSWORD") { "password" } %>
  pool: 5
